// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmVodpFg4585UuKr5HVWkPcyechtayDc',
    appId: '1:415643404278:web:23e80fe887cd8145baa9d7',
    messagingSenderId: '415643404278',
    projectId: 'bmi-app-b5465',
    authDomain: 'bmi-app-b5465.firebaseapp.com',
    storageBucket: 'bmi-app-b5465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCan11ffVospGzFqJ2Y-5j7fWYTwoFE8EA',
    appId: '1:415643404278:android:d056c993ff0069cbbaa9d7',
    messagingSenderId: '415643404278',
    projectId: 'bmi-app-b5465',
    storageBucket: 'bmi-app-b5465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA722A4WU2EdlJEJv5NZQhRntJUjbZuMjU',
    appId: '1:415643404278:ios:1f812b2627f724ddbaa9d7',
    messagingSenderId: '415643404278',
    projectId: 'bmi-app-b5465',
    storageBucket: 'bmi-app-b5465.appspot.com',
    iosClientId:
        '415643404278-g7n04j64ac0m3mh3s1i0v2ibl1c89727.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA722A4WU2EdlJEJv5NZQhRntJUjbZuMjU',
    appId: '1:415643404278:ios:1f812b2627f724ddbaa9d7',
    messagingSenderId: '415643404278',
    projectId: 'bmi-app-b5465',
    storageBucket: 'bmi-app-b5465.appspot.com',
    iosClientId:
        '415643404278-g7n04j64ac0m3mh3s1i0v2ibl1c89727.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp2',
  );
}
